FROM ubuntu:18.04



#RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update  && \
        apt-get install -y python3-pip


COPY ./requirements.txt /opt/Socket/requirements.txt

WORKDIR /opt/Socket


RUN pip3 install -r requirements.txt





COPY . /opt/Socket

RUN pip3 install eventlet
ENTRYPOINT [ "python3" ]

CMD [ "socket2.py" ]
